engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      ignore_warnings: true
      config: .eslintrc
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.scss"

exclude_paths:
- src/assets/fonts/**/*