
siteTitle = "Blog by John Doe"
siteDescr = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. "

authorName = "John Doe"

linkTelegram = "telegram:#"
linkTwitter  = "https://twitter.com/#"
linkGithub 	 = "https://github.com/#"
linkEmail 	 = "#@gmail.com"
linkRss 	 = "/feed.xml"
linkVk 		 = "https://vk.com/#"

linkPrefix = "/lumen"