siteTitle = "Blog by John Doe"
siteDescr = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. "

authorName = "John Doe"

linkTelegram    = "#"
linkTwitter       = "#"
linkGithub 	 = "#"
linkEmail 	 = "#"
linkRss 	 = "/feed.xml"
linkVk 		 = "#"

linkPrefix = "/lumen"