version: 2

jobs:
  test:
    working_directory: ~/gatsby-starter-lumen
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install and build package
          command: yarn install --frozen-lockfile

     - run: 
          name: "Lint"
          command: yarn lint:all

      - run:
          name: Coverage
          command: yarn test:coverage --runInBand --no-cache

      - run:
          name: Unit tests
          command: yarn test --runInBand --no-cache

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  build_test:
    jobs:
      - test